#!/usr/bin/python3
def safe_print_integer(value):
    try:
        print("{:d}".format(value))
        return True and value
    except Exception:
        return False
x =200
boy = safe_print_integer(x) - 1
print(boy)
